const VERSES = [
  {num:1,sanskrit:"चैतन्यमात्मा",translation:"Consciousness is the Self."},
  {num:2,sanskrit:"ज्ञानं बन्धः",translation:"Knowledge is bondage."},
  {num:3,sanskrit:"योनिवर्गः कलाशरीरम्",translation:"The womb of the group of sources is the body of limitation."},
  {num:4,sanskrit:"ज्ञानाधिष्ठानं मातृका",translation:"The matrix is the support of knowledge."},
  {num:5,sanskrit:"उद्यमो भैरवः",translation:"The upsurge is Bhairava."},
  {num:6,sanskrit:"शक्तिचक्रसन्धाने विश्वसंहारः",translation:"By union with the wheel of powers, the universe dissolves."},
  {num:7,sanskrit:"जाग्रद्द्वितीयकरः",translation:"The waking state brings about the second — turīya is experienced even in waking."},
  {num:8,sanskrit:"ज्ञानं जाग्रत्",translation:"Conscious knowledge is the waking state of the teaching."},
  {num:9,sanskrit:"नर्तक आत्मा",translation:"The Self is the actor."},
  {num:10,sanskrit:"रङ्गोऽन्तरात्मा",translation:"The inner Self is the stage."},
  {num:11,sanskrit:"प्रेक्षकाणीन्द्रियाणि",translation:"The senses are the spectators."},
  {num:12,sanskrit:"धीवशात्सत्त्वसिद्धिः",translation:"By the power of the awakened intellect, the attainment of reality."},
  {num:13,sanskrit:"सिद्धः स्वतन्त्रभावः",translation:"The state of perfect freedom is attained."},
  {num:14,sanskrit:"यथा तत्र तथान्यत्र",translation:"As there, so elsewhere — as in the inner, so in the outer."},
  {num:15,sanskrit:"बीजावधानम्",translation:"Attention should be fixed on the seed — the Self."},
  {num:16,sanskrit:"आसनस्थः सुखं ह्रदे निमज्जति",translation:"Seated, one plunges easily into the heart."},
  {num:17,sanskrit:"स्वमात्रानिर्माणमापादयति",translation:"One produces creations according to one's own measure."},
  {num:18,sanskrit:"विद्याविनाशे जन्मविनाशः",translation:"With the dissolution of limited knowledge, birth dissolves."},
  {num:19,sanskrit:"कवर्गादिषु माहेश्वर्याद्याः पशुमातरः",translation:"In the groups beginning with Ka, the powers of the Lord preside as the mothers of bound souls."},
  {num:20,sanskrit:"त्रिषु चतुर्थं तैलवदासेच्यम्",translation:"The fourth should be poured into the three like oil — continuously, without break."},
  {num:21,sanskrit:"मग्नः स्वचित्तेन प्रविशेत्",translation:"Absorbed in one's own consciousness, one should enter."},
  {num:22,sanskrit:"प्राणसमाचारे समदर्शनम्",translation:"In the practice of the breath, the equal vision."},
  {num:23,sanskrit:"मध्येऽवरप्रसवः",translation:"In the middle arises the arising of the lower."},
  {num:24,sanskrit:"मात्रास्वप्रत्ययसन्धाने नष्टस्य पुनरुत्थानम्",translation:"By union of awareness with one's own cognitions, what was lost rises again."},
  {num:25,sanskrit:"शिवतुल्यो जायते",translation:"One becomes equal to Shiva."},
  {num:26,sanskrit:"शरीरवृत्तिर्व्रतम्",translation:"The activity of the body is the vow."},
  {num:27,sanskrit:"कथाजपः",translation:"Ordinary speech is japa."},
  {num:28,sanskrit:"दानमात्मज्ञानम्",translation:"The gift is the knowledge of the Self."},
  {num:29,sanskrit:"योऽविपस्तस्य बीजम्",translation:"The seed of the one who is alert."},
  {num:30,sanskrit:"स्वशक्तिप्रचयोऽस्य विश्वम्",translation:"The universe is the expansion of its own power."},
  {num:31,sanskrit:"स्थितिलयौ",translation:"Establishment and dissolution."},
  {num:32,sanskrit:"तत्प्रवृत्तावप्यनिरासः संवेत्तृभावात्",translation:"Even in that activity, no rejection — due to the nature of the knower."},
  {num:33,sanskrit:"सुखदुःखयोर्बहिर्मननम्",translation:"The contemplation of pleasure and pain is external."},
  {num:34,sanskrit:"तद्विमुक्तस्तु केवली",translation:"Freed from that, one is the alone one."},
  {num:35,sanskrit:"मोहप्रतिसंधाने तुरीयाभोगसम्भवः",translation:"By union with delusion, the experience of the fourth arises."},
  {num:36,sanskrit:"गुरुरुपायः",translation:"The guru is the means."},
  {num:37,sanskrit:"मातृकाचक्रसम्बोधः",translation:"Awakening to the wheel of the matrix."},
  {num:38,sanskrit:"शरीरमावरणम्",translation:"The body is the covering."},
  {num:39,sanskrit:"परिज्ञानेऽन्यदेवाप्ययः",translation:"In full knowledge, the merging into what is other."},
  {num:40,sanskrit:"स्वप्नो विकल्पाः",translation:"Dreams are mental constructs."},
  {num:41,sanskrit:"स्वतन्त्रभावः",translation:"The state of perfect freedom."},
  {num:42,sanskrit:"त्रयस्तदभिन्नाः",translation:"The three are not separate from that."},
  {num:43,sanskrit:"चित्तस्थितिवच्छरीरकरणबाह्येषु",translation:"In the body, senses, and external objects as in the state of mind."},
  {num:44,sanskrit:"भूतकञ्चुकी तदा विमुक्तो भूयः पतिसमः परः",translation:"With the elements as covering, freed then, one is equal to the Lord, supreme."},
  {num:45,sanskrit:"नैसर्गिकः प्राणसम्बन्धः",translation:"The connection with the breath is natural."},
  {num:46,sanskrit:"नासिकान्तर्मध्यसंयमात् किमत्र सव्यापसव्यसौषुम्नेषु",translation:"By restraint in the middle of the nostrils, what need for the left, right, and central channels?"},
  {num:47,sanskrit:"भूयः स्यात्प्रतिमीलनम्",translation:"There is again the closure of the eyes — the return to the inner."},
  {num:48,sanskrit:"नित्यमेतद्गुरुप्रणिहितचेतसः",translation:"Always, for one whose mind is directed by the guru."},
  {num:49,sanskrit:"शक्तिः स्वयं तदर्थं प्रवृत्ता",translation:"The power itself moves toward that purpose."},
  {num:50,sanskrit:"यथाभिमतध्यानाद्वा",translation:"Or through meditation on whatever is desired."},
  {num:51,sanskrit:"कर्मद्वन्द्वे",translation:"In the pair of actions."},
  {num:52,sanskrit:"शक्तिसन्धाने शरीरोत्पत्तिः",translation:"By union with Shakti, the body arises."},
  {num:53,sanskrit:"नाडिसन्धाने भूतजयः",translation:"By union with the channels, mastery of the elements."},
  {num:54,sanskrit:"तस्मान्नित्याभियुक्तस्य तत्सत्त्वात्",translation:"Therefore of the always-united one, from that being."},
  {num:55,sanskrit:"योगिनी भाव",translation:"The state of the yogini — divine feminine consciousness."},
  {num:56,sanskrit:"स्वगुरूपासनम्",translation:"Worship of one's own guru."},
  {num:57,sanskrit:"शिवव्याप्तिः",translation:"The pervasion of Shiva."},
  {num:58,sanskrit:"चितिवह्निरावरोहपदे च्छन्नोऽपि मात्रयाऽभासयत्येव",translation:"The fire of consciousness, even when descended to the lower plane and covered, illumines by its own measure."},
  {num:59,sanskrit:"तत्र विजयते जाग्रत्",translation:"There, waking is victorious."},
  {num:60,sanskrit:"समाधिसंस्कारवतो द्वितीये स्वप्नः",translation:"For one with the impressions of samadhi, in the second state — dream — is also samadhi."},
  {num:61,sanskrit:"तदा सिद्धस्वप्नः",translation:"Then the dream is perfected."},
  {num:62,sanskrit:"चतुर्दशे गतिः",translation:"In the fourteenth — movement to liberation."},
  {num:63,sanskrit:"शिव ईश्वरः",translation:"Shiva is the Lord."},
  {num:64,sanskrit:"जलसमुद्रशक्तिरिव",translation:"Like the power of the ocean within water."},
  {num:65,sanskrit:"तदापरिपूर्णात्",translation:"From that, the non-fullness — limitation arises from moving away."},
  {num:66,sanskrit:"तत् प्रकाशानन्दसारे",translation:"That, in the essence of light and bliss."},
  {num:67,sanskrit:"शुद्धाशुद्धयोर्विशेषाद्भेदाभेदकल्पना",translation:"From the distinction of pure and impure arises the conception of difference and non-difference."},
  {num:68,sanskrit:"आत्मनः स्वयं प्रत्ययो भैरवः",translation:"The self-certifying cognition of the Self is Bhairava."},
  {num:69,sanskrit:"उन्मेषनिमेषौ विश्वस्य सर्गस्थितिसंहृतयः",translation:"The opening and closing of the eyes are the creation, maintenance, and dissolution of the universe."},
  {num:70,sanskrit:"विकल्पसंस्थाने हान्यौ",translation:"In the establishment of differentiated cognition, there is the decrease of bondage."},
  {num:71,sanskrit:"भोगाभोगयोरेकं निदानम्",translation:"Experience and non-experience have one cause."},
  {num:72,sanskrit:"गुणाद्यन्त्रणप्रकाशः",translation:"The manifestation by the mechanism of the qualities."},
  {num:73,sanskrit:"आत्मप्रत्ययसन्धाने विश्वस्य भोगः",translation:"By union with the cognition of the Self, the enjoyment of the universe."},
  {num:74,sanskrit:"चित्तं मन्त्रः",translation:"Consciousness is mantra. The mind saturated with consciousness is the mantra body."},
  {num:75,sanskrit:"स्वप्ने स्वप्नद्रष्टा सत्त्वभूमौ विभाव्यते",translation:"In the dream, the dream-seer is seen in the plane of being."},
  {num:76,sanskrit:"स्वशक्त्यभिव्यक्तिर्विश्वम्",translation:"The universe is the self-manifestation of one's own power."},
  {num:77,sanskrit:"जाग्रत्स्वप्नसुषुप्तभेदे तुर्याभोगसम्भवः",translation:"In the distinction of waking, dream, and deep sleep, the experience of the fourth arises."}
];
